# Generated by Django 4.2.5 on 2023-09-20 00:14

import apps.user.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=255)),
                ('img_perfil', models.ImageField(max_length=500, upload_to=apps.user.models.user_img_directory)),
                ('banner', models.ImageField(max_length=500, upload_to=apps.user.models.user_img_directory)),
                ('bio', models.CharField(max_length=70)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('following', models.IntegerField(blank=True, default=0)),
                ('followers', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
