# Generated by Django 4.2.5 on 2023-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='userbanner.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_perfil',
            field=models.ImageField(default='user-icon.webp', upload_to=''),
        ),
    ]
