# Generated by Django 4.2.5 on 2023-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_slug_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, default='userbanner.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_perfil',
            field=models.ImageField(blank=True, default='user-icon.webp', upload_to=''),
        ),
    ]
