# Generated by Django 4.2.5 on 2023-09-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
    ]
