# Generated by Django 4.2.5 on 2023-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraccount_is_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
