# Generated by Django 4.2.5 on 2023-10-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useraccount_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ('-joined',)},
        ),
    ]
