# Generated by Django 4.2.5 on 2023-09-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
