# Generated by Django 4.2.5 on 2023-09-20 00:14

import apps.server.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(
                    max_length=500, upload_to='images/')),
                ('description', models.TextField(max_length=400)),
                ('published', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='user_name', to='user.user')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='tweet_view_count', to='server.tweet')),
            ],
        ),
    ]
