# Generated by Django 4.2.5 on 2023-09-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='thumbnail',
            field=models.ImageField(blank=True, default='user-icon.webp', null=True, upload_to=''),
        ),
    ]
