# Generated by Django 4.2.5 on 2023-09-21 18:19

import apps.server.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_banner_alter_user_img_perfil'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='thumbnail',
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='user_name', to='user.user'),
        ),
    ]
