# Generated by Django 4.2.5 on 2023-09-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0001_initial'),
        ('server', '0002_alter_tweet_thumbnail_alter_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='thumbnail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='img_url', to='media_upload.photo'),
            preserve_default=False,
        ),
    ]
