# Generated by Django 4.2.5 on 2023-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_tweet_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
