# Generated by Django 4.0 on 2023-10-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_tweet_thumbnail'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='tweet',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
